- added italian translation - applied GstStreamer patch - applied {inputString} patch

diff --git a/kyammi/configure b/kyammi/configure
--- a/kyammi/configure
+++ b/kyammi/configure
@@ -1055,6 +1055,7 @@ Optional Features:
   --disable-rpath         do not use the rpath feature of ld
   --disable-path-check    don't try to find out, where to install
   --disable-xmms          disable support for xmms (don't need xmmsctrl)
+  --disable-gstreamer     disable support for gstreamer
   --disable-ogglibs       disable support of ogglibs for reading/writing ogg
                           tags
   --disable-id3lib        disable support of id3lib for reading id3 tags
@@ -6491,7 +6492,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6494 "configure"' > conftest.$ac_ext
+  echo '#line 6495 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7103,7 +7104,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:7106:" \
+echo "$as_me:7107:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8109,11 +8110,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8112: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8113: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8116: \$? = $ac_status" >&5
+   echo "$as_me:8117: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -8342,11 +8343,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8345: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8346: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8349: \$? = $ac_status" >&5
+   echo "$as_me:8350: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -8409,11 +8410,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8412: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8413: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8416: \$? = $ac_status" >&5
+   echo "$as_me:8417: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10415,7 +10416,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10418 "configure"
+#line 10419 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10513,7 +10514,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10516 "configure"
+#line 10517 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12632,11 +12633,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12635: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12636: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12639: \$? = $ac_status" >&5
+   echo "$as_me:12640: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12699,11 +12700,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12702: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12703: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12706: \$? = $ac_status" >&5
+   echo "$as_me:12707: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13949,7 +13950,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13952 "configure"
+#line 13953 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14047,7 +14048,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14050 "configure"
+#line 14051 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14870,11 +14871,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14873: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14874: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14877: \$? = $ac_status" >&5
+   echo "$as_me:14878: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14937,11 +14938,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14940: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14941: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14944: \$? = $ac_status" >&5
+   echo "$as_me:14945: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16873,11 +16874,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16876: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16877: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16880: \$? = $ac_status" >&5
+   echo "$as_me:16881: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17106,11 +17107,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17109: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17110: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17113: \$? = $ac_status" >&5
+   echo "$as_me:17114: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17173,11 +17174,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17176: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17177: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17180: \$? = $ac_status" >&5
+   echo "$as_me:17181: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19179,7 +19180,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19182 "configure"
+#line 19183 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19277,7 +19278,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19280 "configure"
+#line 19281 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -26574,7 +26575,7 @@ for i in $jpeg_incdirs;
 do
   for j in jpeglib.h;
   do
-    echo "configure: 26577: $i/$j" >&5
+    echo "configure: 26578: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       jpeg_incdir=$i
@@ -26879,7 +26880,7 @@ for i in $qt_incdirs;
 do
   for j in $kde_qt_header;
   do
-    echo "configure: 26882: $i/$j" >&5
+    echo "configure: 26883: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       qt_incdir=$i
@@ -27696,7 +27697,7 @@ for i in $kde_incdirs;
 do
   for j in $kde_check_header;
   do
-    echo "configure: 27699: $i/$j" >&5
+    echo "configure: 27700: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_incdir=$i
@@ -27726,7 +27727,7 @@ for i in $kde_libdirs;
 do
   for j in $kde_check_lib;
   do
-    echo "configure: 27729: $i/$j" >&5
+    echo "configure: 27730: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_libdir=$i
@@ -27744,7 +27745,7 @@ for i in $kde_libdirs;
 do
   for j in "kde3/plugins/designer/kdewidgets.la";
   do
-    echo "configure: 27747: $i/$j" >&5
+    echo "configure: 27748: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       kde_widgetdir=$i
@@ -29192,7 +29193,7 @@ for i in $kde_sharedirs;
 do
   for j in apps/ksgmltools2/customization/kde-chunk.xsl;
   do
-    echo "configure: 29195: $i/$j" >&5
+    echo "configure: 29196: $i/$j" >&5
     if test -r "$i/$j"; then
       echo "taking that" >&5
       KDE_XSL_STYLESHEET=$i
@@ -29614,12 +29615,22 @@ _ACEOF
 
 
 
+
+
 # Check whether --enable-xmms or --disable-xmms was given.
 if test "${enable_xmms+set}" = set; then
   enableval="$enable_xmms"
   configure_enable_xmms=$enableval
 else
   configure_enable_xmms=yes
+fi;
+
+# Check whether --enable-gstreamer or --disable-gstreamer was given.
+if test "${enable_gstreamer+set}" = set; then
+  enableval="$enable_gstreamer"
+  configure_enable_gstreamer=$enableval
+else
+  configure_enable_gstreamer=yes
 fi;
 
 # Check whether --enable-ogglibs or --disable-ogglibs was given.
@@ -29641,12 +29652,14 @@ fi;
 { echo "$as_me:$LINENO:
  Requested:
  XMMS support .........: $configure_enable_xmms
+ gstreamer support ....: $configure_enable_gstreamer
  ogglibs support ......: $configure_enable_ogglibs
  id3lib support .......: $configure_enable_id3lib
  " >&5
 echo "$as_me:
  Requested:
  XMMS support .........: $configure_enable_xmms
+ gstreamer support ....: $configure_enable_gstreamer
  ogglibs support ......: $configure_enable_ogglibs
  id3lib support .......: $configure_enable_id3lib
  " >&6;}
@@ -30314,6 +30327,176 @@ _ACEOF
 
 fi
 
+#dnl GStreamer Support
+if test "x$configure_enable_gstreamer" = "xyes"; then
+
+
+
+
+   kde_safe_cppflags=$CPPFLAGS
+   CPPFLAGS="$CPPFLAGS $all_includes"
+    ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ac_link='rm -rf SunWS_cache; ${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+
+
+   if test "${ac_cv_header_kde_gstplay_play_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for kde/gstplay/play.h" >&5
+echo $ECHO_N "checking for kde/gstplay/play.h... $ECHO_C" >&6
+if test "${ac_cv_header_kde_gstplay_play_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_kde_gstplay_play_h" >&5
+echo "${ECHO_T}$ac_cv_header_kde_gstplay_play_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking kde/gstplay/play.h usability" >&5
+echo $ECHO_N "checking kde/gstplay/play.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* #line $LINENO "configure" */
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <kde/gstplay/play.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking kde/gstplay/play.h presence" >&5
+echo $ECHO_N "checking kde/gstplay/play.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* #line $LINENO "configure" */
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <kde/gstplay/play.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: kde/gstplay/play.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: kde/gstplay/play.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: kde/gstplay/play.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: kde/gstplay/play.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: kde/gstplay/play.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: kde/gstplay/play.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: kde/gstplay/play.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: kde/gstplay/play.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: kde/gstplay/play.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: kde/gstplay/play.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for kde/gstplay/play.h" >&5
+echo $ECHO_N "checking for kde/gstplay/play.h... $ECHO_C" >&6
+if test "${ac_cv_header_kde_gstplay_play_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_kde_gstplay_play_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_kde_gstplay_play_h" >&5
+echo "${ECHO_T}$ac_cv_header_kde_gstplay_play_h" >&6
+
+fi
+if test $ac_cv_header_kde_gstplay_play_h = yes; then
+  configure_enable_gstreamer=yes
+else
+  configure_enable_gstreamer=no
+fi
+
+
+   CPPFLAGS=$kde_safe_cppflags
+   ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+
+   if test "x$configure_enable_gstreamer" = "xyes"; then
+      cat >>confdefs.h <<\_ACEOF
+#define ENABLE_GSTREAMER
+_ACEOF
+
+      LIBS="$LIBS -lkdegst -lkdegstplay"
+   fi
+fi
 
 
 
@@ -30327,6 +30510,7 @@ Configuration for $PACKAGE $VERSION :
  Compiler .............: $CC $CFLAGS $LIBFLAC_CFLAGS
  Linker ...............: $CC $LDFLAGS $LIBS $LIBFLAC_LIBS
  XMMS support .........: $configure_enable_xmms
+ gstreamer support ....: $configure_enable_gstreamer
  ogglibs support ......: $configure_enable_ogglibs
  id3lib support .......: $configure_enable_id3lib
  Install path .........: $prefix
@@ -30348,6 +30532,7 @@ Configuration for $PACKAGE $VERSION :
  Compiler .............: $CC $CFLAGS $LIBFLAC_CFLAGS
  Linker ...............: $CC $LDFLAGS $LIBS $LIBFLAC_LIBS
  XMMS support .........: $configure_enable_xmms
+ gstreamer support ....: $configure_enable_gstreamer
  ogglibs support ......: $configure_enable_ogglibs
  id3lib support .......: $configure_enable_id3lib
  Install path .........: $prefix
