prepared for distribution (tar.gz) (trouble with kdevelop crashing on autoconf/automake)

diff --git a/HEAD/configure b/HEAD/configure
--- a/HEAD/configure
+++ b/HEAD/configure
@@ -19902,7 +19902,7 @@ echo "${ECHO_T}$install_it" >&6
   fi
 done
 
-ac_config_files="$ac_config_files Makefile yammi/Makefile"
+ac_config_files="$ac_config_files Makefile yammi/Makefile yammi/docs/Makefile yammi/docs/en/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -20224,9 +20224,11 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "yammi/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/Makefile" ;;
+  "yammi/docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/docs/Makefile" ;;
+  "yammi/docs/en/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/docs/en/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:20229: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:20231: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -20532,7 +20534,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:20535: creating $ac_file" >&5
+    { echo "$as_me:20537: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -20550,7 +20552,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20553: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20555: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20563,7 +20565,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20566: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20568: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20624,7 +20626,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:20627: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:20629: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -20635,7 +20637,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20638: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20640: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20648,7 +20650,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20651: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20653: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20765,7 +20767,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:20768: $ac_file is unchanged" >&5
+      { echo "$as_me:20770: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
