testing for compile farm

diff --git a/HEAD/configure b/HEAD/configure
--- a/HEAD/configure
+++ b/HEAD/configure
@@ -20138,7 +20138,7 @@ echo "${ECHO_T}$install_it" >&6
   fi
 done
 
-ac_config_files="$ac_config_files Makefile yammi/Makefile yammi/docs/Makefile yammi/docs/en/Makefile yammi/icons/Makefile yammi/mp3info/Makefile"
+ac_config_files="$ac_config_files Makefile yammi/Makefile yammi/mp3info/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -20460,13 +20460,10 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "yammi/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/Makefile" ;;
-  "yammi/docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/docs/Makefile" ;;
-  "yammi/docs/en/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/docs/en/Makefile" ;;
-  "yammi/icons/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/icons/Makefile" ;;
   "yammi/mp3info/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/mp3info/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:20469: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:20466: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -20772,7 +20769,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:20775: creating $ac_file" >&5
+    { echo "$as_me:20772: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -20790,7 +20787,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20793: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20790: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20803,7 +20800,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20806: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20803: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20864,7 +20861,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:20867: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:20864: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -20875,7 +20872,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20878: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20875: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20888,7 +20885,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20891: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20888: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -21005,7 +21002,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:21008: $ac_file is unchanged" >&5
+      { echo "$as_me:21005: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
