lots of basic changes: - started using id3lib - used CMP3Info for layer info - ...

diff --git a/HEAD/configure b/HEAD/configure
--- a/HEAD/configure
+++ b/HEAD/configure
@@ -19902,7 +19902,7 @@ echo "${ECHO_T}$install_it" >&6
   fi
 done
 
-ac_config_files="$ac_config_files Makefile yammi/Makefile yammi/docs/Makefile yammi/docs/en/Makefile"
+ac_config_files="$ac_config_files Makefile yammi/Makefile yammi/docs/Makefile yammi/docs/en/Makefile yammi/icons/Makefile yammi/mp3info/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -20226,9 +20226,11 @@ do
   "yammi/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/Makefile" ;;
   "yammi/docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/docs/Makefile" ;;
   "yammi/docs/en/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/docs/en/Makefile" ;;
+  "yammi/icons/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/icons/Makefile" ;;
+  "yammi/mp3info/Makefile" ) CONFIG_FILES="$CONFIG_FILES yammi/mp3info/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:20231: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:20233: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -20534,7 +20536,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:20537: creating $ac_file" >&5
+    { echo "$as_me:20539: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -20552,7 +20554,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20555: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20557: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20565,7 +20567,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20568: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20570: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20626,7 +20628,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:20629: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:20631: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -20637,7 +20639,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20640: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20642: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20650,7 +20652,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20653: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20655: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20767,7 +20769,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:20770: $ac_file is unchanged" >&5
+      { echo "$as_me:20772: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
